// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH7PpqwgjpIqxfC9z1UQW-TjFyAZtNQWo',
    appId: '1:490259590896:web:045590873e7ea4ecb95c35',
    messagingSenderId: '490259590896',
    projectId: 'sivo-in',
    authDomain: 'sivo-in.firebaseapp.com',
    storageBucket: 'sivo-in.firebasestorage.app',
    measurementId: 'G-DD98FHZ2QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt_cAT5z3tCoTpxEJpX0Fil6POcNkSuwg',
    appId: '1:490259590896:android:4704587f3ad38f12b95c35',
    messagingSenderId: '490259590896',
    projectId: 'sivo-in',
    storageBucket: 'sivo-in.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_RT9einY6N9szAFOWjFUxy0DNDB-LXN4',
    appId: '1:490259590896:ios:daaf329da79b797eb95c35',
    messagingSenderId: '490259590896',
    projectId: 'sivo-in',
    storageBucket: 'sivo-in.firebasestorage.app',
    iosBundleId: 'com.example.rivusUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_RT9einY6N9szAFOWjFUxy0DNDB-LXN4',
    appId: '1:490259590896:ios:daaf329da79b797eb95c35',
    messagingSenderId: '490259590896',
    projectId: 'sivo-in',
    storageBucket: 'sivo-in.firebasestorage.app',
    iosBundleId: 'com.example.rivusUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH7PpqwgjpIqxfC9z1UQW-TjFyAZtNQWo',
    appId: '1:490259590896:web:ed1c2f734855945bb95c35',
    messagingSenderId: '490259590896',
    projectId: 'sivo-in',
    authDomain: 'sivo-in.firebaseapp.com',
    storageBucket: 'sivo-in.firebasestorage.app',
    measurementId: 'G-Y54K9K3R8T',
  );

}